import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Custom/custom_components.exports.js";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body>
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  );
}
