import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Custom/custom_components.exports.js";
import Footer from "@/components/Custom/Footer";
import GlobalPageLoader from "@/components/Custom/GlobalPageLoader";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body>
        <GlobalPageLoader />
        <Navbar />
        <div>{children}</div>
        <Footer />
        <Toaster position="top-right" richColors closeButton duration={4000} />
      </body>
    </html>
  );
}
