import type { Metadata } from "next";
import {
  ContactUs,
  Navbar,
  Testimonials,
} from "@/components/Custom/custom_components.exports.js";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ServiceLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="services-layout">
      <Navbar />
      <div className="my-20">{children}</div>
      <Testimonials />
      <ContactUs />
    </section>
  );
}
